# Generated by Django 5.0 on 2023-12-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
