# Generated by Django 5.0 on 2024-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
