# Generated by Django 5.0 on 2024-01-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogmodel_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='file_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
